name: circuit_stem
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame_audio: ^2.11.8
  shared_preferences: ^2.5.3
  flame: ^1.11.0
  flutter_svg: ^2.2.0
  vector_graphics: ^1.1.19
  google_fonts: ^6.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  state_notifier: 1.0.0
  flutter_hooks: ^0.20.1
  rxdart: ^0.27.7
  provider: ^6.0.5
  flutter_riverpod: 2.6.1
  hooks_riverpod: 2.6.1
  riverpod: 2.6.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/levels/
