# name: CI

# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   analyze_and_test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: stable
#       - name: Install dependencies
#         run: flutter pub get
#       - name: Format check
#         run: flutter format --set-exit-if-changed .
#       - name: Analyze
#         run: flutter analyze
#       - name: Run tests
#         run: flutter test --coverage
